### ISSUE TITLE
ValueError when setting a ParamList's value in __init__

### ISSUE THREAD

**Issue by kennedy0** [cmontesano/xappt#11]
Due to the `ValidateChoiceList` validator, setting a list's value by calling a `BaseTool` with the parameter value in the kwargs throws an error if the parameter doesn't have any choices by default.

This is where the problem occurs:
https://github.com/cmontesano/xappt/blob/b53d7d761fee812de818c128191443a67bbd049b/xappt/models/plugins/tool.py#L19

Example:
```python
@xappt.register_plugin
class ToolA(xappt.BaseTool):
    def execute(self, **kwargs) -> int:
        test_list = ["apple", "banana", "carrot", "doughnut"]
        return self.interface.invoke(ToolB(test_param=test_list))



@xappt.register_plugin
class ToolB(xappt.BaseTool):
    test_param = xappt.ParamList()
    def __init__(self, interface: xappt.BaseInterface, **kwargs):
        super().__init__(interface=interface, **kwargs)
```

**Comment by cmontesano** [comment]
I think I understand the issue. I believe your intention is to specify the items with which to populate the list (the `choices`) during `__init__`. However the current behaviour then specifying a parameter during `__init__` is to set the value, not the choices.
So, we need to figure out how to specify choices during `__init__`. Maybe we can support passing in a dictionary to specify more than just the value.

**Comment by cmontesano** [comment]
I have a change cooking that will allow you to set `default`, `required`, `choices`, `options`, `value`, and `metadata` in that order, which is the same order in which these attributes are first initialized.

Does this look ok?

```python
import xappt


@xappt.register_plugin
class ToolA(xappt.BaseTool):
    def execute(self, **kwargs) -> int:
        test_init = {
            'choices': ["apple", "banana", "carrot", "doughnut"],
            'value': "banana",
        }
        return self.interface.invoke(ToolB(self.interface, test_param=test_init))


@xappt.register_plugin
class ToolB(xappt.BaseTool):
    test_param = xappt.ParamList()

    def __init__(self, interface: xappt.BaseInterface, **kwargs):
        super().__init__(interface=interface, **kwargs)

    def execute(self, **kwargs) -> int:
        return 0


if __name__ == '__main__':
    iface = xappt.get_interface("stdio")
    tool = ToolA(interface=iface)
    tool.execute()
```

We currently don't have any parameters that take a dict value, but I suppose that could be a possibility in the future. Maybe this should be a simple dict subclass - that way we can check against a specific type of object. It would also give us named attributes making it more intuitive to use:

**Comment by cmontesano** [comment]
I'll be pushing a branch shortly with the dict subclass:

```python
@xappt.register_plugin
class ToolA(xappt.BaseTool):
    def execute(self, **kwargs) -> int:
        test_init = xappt.ParamSetupDict(choices=["apple", "banana", "carrot", "doughnut"],
                                         value="banana")
        return self.interface.invoke(ToolB(self.interface, test_param=test_init))
```
