### ISSUE TITLE
Allow plugin discovery to import modules with the same name

### ISSUE THREAD

**Issue by kennedy0** [cmontesano/xappt#26]
When multiple modules are found on the `XAPPT_PLUGIN_PATH` with the same name, only the first one is imported.

It would be great if we could find a way for xappt's plugin manager to handle these conflicts.

**Comment by cmontesano** [comment]
So as discussed, this is pretty problematic. For this to work we have to manipulate `sys.path` which raises even more complications.
As a compromise, I've reworked plugin discovery, and a warning will be logged when a module name conflict is detected.

See 9d16e31f72ca05532398c41e71255400f8a81efa
